FROM openjdk:17-alpine

# Set environment variables for Gradle
ENV GRADLE_VERSION=8.4 \
    GRADLE_HOME=/opt/gradle

# Install dependencies
RUN apk --no-cache add curl \
    && mkdir -p /opt \
    && mkdir -p /app/src/main/java/examples \
    && curl -L https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle.zip \
    && unzip -d /opt /tmp/gradle.zip \
    && ln -s /opt/gradle-${GRADLE_VERSION} ${GRADLE_HOME} \
    && rm -rf /tmp/gradle.zip
    

ENV PATH="${GRADLE_HOME}/bin:${PATH}"

# Set the working directory
WORKDIR /app

# Copy the Java file into the container
COPY ProducerExample.java /app/src/main/java/examples
COPY getting-started.properties /app
COPY build.gradle /app

# Build the project
RUN gradle build
RUN gradle shadowJar

# Run the Java application to produce data to Kafka

#Explore container with docker run -it producer /bin/sh