FROM openjdk:17-alpine

# Set environment variables for Gradle
ENV GRADLE_VERSION=8.4 \
    GRADLE_HOME=/opt/gradle

# Install dependencies
RUN apk --no-cache add curl \
    && mkdir -p /opt \
    && mkdir -p /app/src/main/java/sensors \
    && mkdir -p /app/data \
    && curl -L https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle.zip \
    && unzip -d /opt /tmp/gradle.zip \
    && ln -s /opt/gradle-${GRADLE_VERSION} ${GRADLE_HOME} \
    && rm -rf /tmp/gradle.zip 

ENV PATH="${GRADLE_HOME}/bin:${PATH}"\
    PRODUCER_ID=1

# Set the working directory
WORKDIR /app

# Copy the Java file into the container
COPY build.gradle /app
COPY SensorProducerApplication.java /app/src/main/java/sensors
COPY RTproducer.properties /app
#COPY sensor_0.json /app/data

# Build the project (docker compose)
RUN gradle build
RUN gradle shadowJar

# Run the Java application to produce data to Kafka (docker compose)
# CMD java -cp build/libs/kafka-producer-sensor-0.0.1.jar sensors.SensorProducerApplication RTproducer.properties data/sensor_0.json

# Explore container with docker run -it producer /bin/sh